transform_data_bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: gg-bigquery-datawarehouse
      dataset: SilverLayer
      threads: 4 # Must be a value of 1 or greater
      keyfile: ../google-key.json
      OPTIONAL_CONFIG: VALUE